from rdflib import URIRef

RDF_TYPE = URIRef("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")

TM_CLASS = URIRef("http://w3id.org/rml/TriplesMap")
LOGICAL_SOURCE = URIRef("http://w3id.org/rml/logicalSource")
LOGICAL_SOURCE_CLASS = URIRef("http://w3id.org/rml/LogicalSource")
REF_FORMULATION = URIRef("http://w3id.org/rml/referenceFormulation")
CSV_FORMAT = URIRef("http://w3id.org/rml/CSV")
SOURCE = URIRef("http://w3id.org/rml/source")
PATH_SOURCE_CLASS = URIRef("http://w3id.org/rml/RelativePathSource")
ROOT_DIR = URIRef("http://w3id.org/rml/root")
MAPPING_DIR = URIRef("http://w3id.org/rml/MappingDirectory")
MAPPING_PATH = URIRef("http://w3id.org/rml/path")

SUBJECT_MAP = URIRef("http://w3id.org/rml/subjectMap")
TEMPLATE = URIRef("http://w3id.org/rml/template")
CONSTANT = URIRef("http://w3id.org/rml/constant")
REFERENCE = URIRef("http://w3id.org/rml/reference")
TERM_TYPE = URIRef("http://w3id.org/rml/termType")
POM = URIRef("http://w3id.org/rml/predicateObjectMap")
PREDICATE_MAP = URIRef("http://w3id.org/rml/predicateMap")
OBJECT_MAP = URIRef("http://w3id.org/rml/objectMap")
GRAPH_MAP = URIRef("http://w3id.org/rml/graphMap")
DATATYPE_MAP = URIRef("http://w3id.org/rml/datatypeMap")
REF_OBJ_MAP = URIRef("http://w3id.org/rml/RefObjectMap")
JOIN_COND = URIRef("http://w3id.org/rml/joinCondition")
CHILD = URIRef("http://w3id.org/rml/child")
PARENT = URIRef("http://w3id.org/rml/parent")
PARENT_TM = URIRef("http://w3id.org/rml/parentTriplesMap")


IRI = URIRef("http://w3id.org/rml/IRI")
BLANKNODE = URIRef("http://w3id.org/rml/BlankNode")
LITERAL = URIRef("http://w3id.org/rml/Literal")